version: "3.9"
services:
  streamlit_app:
    build:
      context: ./webapp
    ports:
      - "8501:8501"
    networks:
      - app_network
  fastapi_app:
    build:
      context: ./serving
    volumes:
      - ./artifacts:/artifacts
      - ./data:/data
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
